# This worklow start when a GitHub Release is created
name : Deploy on Release

# Controls the event triggering the workflow
on :
  release :
    types : [created]

jobs :

  test-branch-workflow :
    uses : Ecole-des-Ponts-ParisTech/BRIDGES/.github/workflows/dotnet_test.yml@master

  deploy-nuget-workflow :
    needs: test-branch-workflow
    uses : Ecole-des-Ponts-ParisTech/BRIDGES/.github/workflows/deploy_nuget.yml@master

  deploy-nuget-workflow :
    needs: deploy-nuget
    uses : Ecole-des-Ponts-ParisTech/BRIDGES/.github/workflows/deploy_docfx_pages.yml@master
