name: .Net Test

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Check-out Repository
      uses: actions/checkout@v3

    - name: Setup .Net
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name : Build Solution
      run: dotnet build --configuration Release

    - name : Test Project
      run: dotnet test --verbosity normal

